### ISSUE TITLE
Handle binary project first

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/cdog#1]
```
-project/
  |-cdog.toml
  \-src/
     |- main.cc
     |- add.cc
     \- add.h
```

In cdog.toml

```toml
[package]
bin = "build"
src = "src"
```

Using command `cdog build`, you will get a binary called `build/project` compiled from `src/main.cc`.

In main.cc you can use add.h like

```cpp
#include "add.h"
```

Because src will become default include dir.
