### ISSUE TITLE
[Feat]Generate Project Structure

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/cdog#11]
If command is

```bash
$ cdog new Project
```

Result is

```
Project/
 |-Cdog.toml
 |-src/
    |-main.cpp
```

**Comment by dannypsnl** [comment]
Should in `Cdog.toml`
```toml
[package]
name = "Project"
version = "0.1.0"
compiler = "g++"
```
