### ISSUE TITLE
Support overwrite the command

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/cdog#14]
It just likes #13 purpose, it can help an existing library don't need to do too many for Cdog.

It can keep its original build system.

**Comment by dannypsnl** [comment]
Read configure to detected having command or not.

For example

```toml
[commands]
build = "cd build && cmake .. && make && make test && cd .."
```

When executing `cdog build`, the command write in Toml will be invoked.
